id: I2E100092
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:52:10.138388
last_modified: 2023-02-09 14:52:10.138505
source_metadata:
  title: 'PP: Vajracchedikā Prajñāpāramitā'
  language: zh
bases:
  F67C:
    base_file: F67C.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
